server:
  port: 8888
  servlet:
    context-path: /myChat_server

spring:
  datasource:
    name: myChatDB
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///myChatDB
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 19951122
    filters: stat
    initialSize: 2
    maxIdle: 10
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableTimeMillis: 300000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false

#为了访问web-inf 下面的页面 view resolver
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp




